### ISSUE TITLE
ISBAT PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error

### ISSUE THREAD

**Issue by thefrosty** [godaddy-wordpress/coblocks#2386]
### Describe the bug:
Fatal error being thrown:
```
PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /srv/users/.../plugins/coblocks/src/blocks/gist/index.php:50
Stack trace:
#0 /srv/users/.../wp-includes/class-wp-embed.php(156): coblocks_block_gist_handler(Array, Array, 'https://gist.gi...', Array)
#1 /srv/users/.../wp-includes/class-wp-embed.php(219): WP_Embed->get_embed_handler_html(Array, 'https://gist.gi...')
#2 /srv/users/.../wp-includes/class-wp-embed.php(463): WP_Embed->shortcode(Array, 'https://gist.gi...')
#3 [internal function]: WP_Embed->autoembed_callback(Array)
#4 /srv/users/.../wp-includes/class-wp-embed.php(445): preg_replace_callback('|^(\\s*)(https?:...', Array, '<!-- wp:paragra...')
#5 /srv/users/...wp-includes/class-wp-hook.php(307): WP_Embed->autoembed('<!-- wp:paragra...')
#6 /srv/users/.../wp-includes/plugin.php( in /srv/users/.../wp-content/plugins/coblocks/src/blocks/gist/index.php on line 50
```

### To reproduce:
Log into WP Admin, note all dashboard widgets missing.

### Expected behavior:
No error, or blocker in admin index dashboard page.

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:
5.9.3

### PHP version:
7.4.29

**Comment by thefrosty** [comment]
No validations exists for when an API response is bad: https://github.com/godaddy-wordpress/coblocks/blob/ab723207271e39ba97969192067f12e9415d362d/src/blocks/gist/index.php#L39
